name: Keep Multiple Streamlit Apps Awake

on:
  schedule:
    # 6時間おきに実行
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping_apps:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Apps
        run: |
          curl -I -L https://ri2maps-app-mlsmfzqnbdkaengohbxwwg.streamlit.app/
          curl -I -L https://platformroad2-wlyzi2hiypbncesd8yyx9q.streamlit.app/
          curl -I -L https://my-jartic-app-cjxyuqz6kfvfaa2xxhfhgh.streamlit.app/
          curl -I -L https://road-consultation-app-vc5etwmzjrgni8zgp6seul.streamlit.app/
